[FIX] VCS 작업 관련 추가적인 예외처리
CAU-OSS-2023-Team15/Project-1 pull request #26
Opened 2023-05-09 12:59 UTC by yymin1022

## Summary
- VCS 작업 과정의 예외처리를 추가 구현하였습니다.

## Description
- `Modified File`에 대한 조건문에 있는 모호성 문제를 해결하였습니다.
- 밤샘작업 과정에서 불필요한 변수가 추가된 것을 제거하였습니다.
- 공백이 포함된 경로에서 `git init` 혹은 `git status`가 실행되지 않던 이슈를 해결하였습니다.
- `git commit` 기능이 `Staged File`이 존재하는 경우에만 작동하도록 개선하였습니다.

2023-05-09 13:27 UTC, sehwanii approved these changes, later dismissed
자칫 넘기기 쉬운 예외처리도 꼼꼼하게 해결 한 것 같습니다! 고생하셨습니다!

2023-05-09 13:28 UTC, falconlee236 submitted a review, later dismissed
몇가지 추가적인 예외가 있었네요 git status의 축약표현에 대해 알아봐야할거 같습니다

2023-05-09 13:38 UTC, jiyuneel requested changes
새로운 파일을 add하면 `git status -s`를 했을 때 A가 표시되는데 이 경우에 대한 처리도 추가해야 할 것 같습니당!

2023-05-09 16:34 UTC, yymin1022 commented
[Git 공식 문서](https://git-scm.com/docs/git-status)를 참조하여 `git status -s` 명령의 모든 결과 형태에 대한 조건처리를 추가 구현하였습니다.

2023-05-09 16:43 UTC, jiyuneel approved these changes
`git status -s` 결과로 나오는 status 형태가 생각했던 것보다 훨씬 많았네요...!!

2023-05-09 20:34 UTC, falconlee236 approved these changes
너무 조건이 많아요 ㅠㅠ 이걸 다들 어떻게 처리하셨는지 존경스럽네요

2023-05-10 01:56 UTC, sehwanii approved these changes
조건 분기가 정말 많네요 꼼꼼하게 다 체크하시느라 고생하셨습니다!

2023-05-10 03:54 UTC, yymin1022 commented
`main` 브랜치 Merge Conflice 해결하였습니다.

2023-05-10 03:54 UTC, merged