Dev/git commit history
CAU-OSS-2023-Team15/Project-1 pull request #43
Opened 2023-06-04 07:32 UTC by sehwanii

## Summary
Git repository에서 git graph를 확인할 수 있는 기능을 추가하였습니다.
### Description

상단에 Git History Button을 추가하여 클릭시 Commit History Grpah
- 현재 위치의 Repository가 Git repository가 아니라면 notification을 화면에 출력합니다.
![1](https://github.com/CAU-OSS-2023-Team15/Project-1/assets/52828497/dc031f5f-b29c-4acd-a138-21e66a3f9264)
- 현재 위치의 Repository가 Git repository라면 Git log graph를 새로운 창에 출력합니다.
![2](https://github.com/CAU-OSS-2023-Team15/Project-1/assets/52828497/824ee228-4081-45f0-880e-1c088340ee6d)
- Git log graph에서 해당 commit을 클릭 시, commit에 대한 상세 정보를 확인 할 수 있습니다.
![3](https://github.com/CAU-OSS-2023-Team15/Project-1/assets/52828497/d2fd7d30-a90a-42fa-b5e3-b4375a0b5937)

2023-06-04 07:52 UTC, yymin1022 requested changes
특정 `Commit`의 상세 정보를 표시할 때, `git diff` 항목이 누락된 것 같습니다.
이외의 구현은 충분한 것 같으니, `diff` 내용만 추가 구현 부탁드립니다!

2023-06-10 09:15 UTC, yymin1022 commented
다음과 같은 이슈를 개선작업하였습니다.
- 특정 상황의 Commit 클릭 시, 상세정보가 정상적으로 표시되지 않던 문제
- Git History Log에서 Commit Hash를 제외한 Author 및 Message 정보가 표시되지 않던 문제
- 일부 IPC 관련 로직 개선

2023-06-10 09:16 UTC, yymin1022 approved these changes

2023-06-10 09:16 UTC, yymin1022 commented on src/git_history.html
> +            font-size: 15px;
Git Log 관련 CSS 속성을 조정하여 가독성을 개선하였습니다.

2023-06-10 09:22 UTC, falconlee236 approved these changes
문자열 parsing이 정말 귀찮으셨을 텐대 정말 대단합니다 선생님

2023-06-10 11:55 UTC, jiyuneel approved these changes
굉장한 작업이네요! 고생 많으셨습니다 🙌🏻

2023-06-10 11:56 UTC, merged