[DEV] VCS - Github Clone
CAU-OSS-2023-Team15/Project-1 pull request #44
Opened 2023-06-04 17:17 UTC by jiyuneel

## Summary
* `git clone` 기능을 구현하였습니다.

## Description
* 상단 메뉴의 Git Clone 버튼을 클릭하면 clone 관련 dialog가 뜹니다.
* 버튼을 통해 public 또는 private 중에 선택할 수 있습니다.
* **public repository**의 경우, 입력한 Github Repository Address가 clone 됩니다.
* **private repository**의 경우, 입력한 Github ID와 Access Token이 _GithubInfo.txt_ 파일에 저장됩니다.

<img width="873" alt="스크린샷 2023-06-05 오전 2 16 46" src="https://github.com/CAU-OSS-2023-Team15/Project-1/assets/63193220/666e2589-abc9-4d3d-8d6f-9a82344dc7ba">

2023-06-04 17:30 UTC, yymin1022 requested changes

2023-06-04 17:30 UTC, yymin1022 commented on main.js
> +    let checkGitRepo = `cd ${dirPath} && git status -s`;
여기서 현재 디렉토리가 Git Repository인지에 대한 체크가 실행되는데, 이부분을 제거하고 어느 디렉토리에서든 실행 가능하게 해야할 것 같습니다!

2023-06-04 17:30 UTC, yymin1022 commented on src/git_clone_dialog.html
> +        <div style="padding: 20px 10px;">
`Clone` 버튼과 `Cancel` 버튼의 색상을 변경하면 좋을 것 같습니다.
현재는 `Clone` 버튼이 `red` 색상으로, `Cancel` 버튼이 `default` 색상으로 되어있는데, 두 색상을 서로 스왑하면 좀 더 UX상으로 개선될 수 있을 것 같습니다.

2023-06-04 17:36 UTC, jiyuneel commented on main.js
> +    let checkGitRepo = `cd ${dirPath} && git status -s`;
확인했습니당!-! 👩🏻‍💻

2023-06-04 17:50 UTC, yymin1022 requested changes

2023-06-04 17:50 UTC, yymin1022 commented on main.js
> +    let cmd = `cd ${filePath} && echo \"${github_id}\n${github_access_token}\" > GithubInfo.txt`;
`Private Repository`에 대한 동작에서, 계정 정보를 로컬 파일로 기록하는 로직은 존재하나, 실질적으로 `git clone`이 수행되는 로직이 누락되어있습니다.

2023-06-04 17:51 UTC, yymin1022 requested changes

2023-06-04 17:51 UTC, yymin1022 commented on main.js
> +    let cmd = `cd ${filePath} && echo \"${github_id}\n${github_access_token}\" > GithubInfo.txt`;
Private Repository에 대한 동작에서, 계정 정보를 로컬 파일로 기록하는 로직은 존재하나, 실질적으로 git clone이 수행되는 로직이 누락되어있습니다.

2023-06-05 00:57 UTC, falconlee236 requested changes
git clone에 대한 기능적 구현 뿐만 아니라 UI적으로 조금만 다듬어서 커밋하면 될것 같습니다
얼마 안남았어요 화이팅!!

2023-06-05 00:57 UTC, falconlee236 commented on src/git_clone_dialog.html
> +        <div class="ui h5 warning" style="padding: 30px 0px 0px 0px;">
public radio button을 누르면 이 div 부분은 나오지 않게 만드는 것이 좋을것 같습니다. (Additional Information for Private Repository)
반대로 private radio button을 누르면 public 부분은 나오는게 좋을것 같습니다

2023-06-05 00:57 UTC, falconlee236 commented on main.js
> +    exec(cmd, (error, stdout, stderr) => {
clone이 성공할때나, 실패할때나 아래에 작은 message를 달면 좋을것 같습니다.
```javascript
BrowserWindow.getFocusedWindow().send(
                "notification",
                error.message
            );
```
이 코드 사용하면 좋아요!

2023-06-05 14:07 UTC, jiyuneel commented on main.js
> +    exec(cmd, (error, stdout, stderr) => {
의견 감사합니다~!! 🙌🏻👩🏻‍💻

2023-06-05 17:16 UTC, jiyuneel commented on main.js
> +    let cmd = `cd ${filePath} && echo \"${github_id}\n${github_access_token}\" > GithubInfo.txt`;
가장 중요한 걸...! 알려주셔서 감사합니다 😸

2023-06-05 17:17 UTC, jiyuneel commented on src/git_clone_dialog.html
> +        <div class="ui h5 warning" style="padding: 30px 0px 0px 0px;">
좋은 의견 감사해용 :)

2023-06-05 17:59 UTC, yymin1022 requested changes
확인했습니다!
`git clone` 기능 자체는 잘 동작하는데, `GithubInfo.txt`를 이용한 자동로그인이 누락된 것 같습니다. 추가 코멘트 남긴 항목들 확인 부탁드려요!

2023-06-05 17:59 UTC, yymin1022 commented on main.js
> +        // confirm.send("confirm_git_clone", current_directory);
불필요주석 제거 부탁드립니다!

2023-06-05 17:59 UTC, yymin1022 commented on main.js
> +    BrowserWindow.getFocusedWindow().send("refresh");
`Public Repository`를 Clone 한 뒤에 화면이 새로고침되면서 UI가 두 번 표시되는 이슈가 있습니다. 이부분이 이전에 다른 기능 개발하면서도 나타났던 이슈인데, `"refresh"` 시그널 전송 로직 위치를 바꾸면 해결되었던 것 같아요!
`Private Repository` Clone 파트랑은 다르게 `"refresh"` 시그널 로직이 `exec` 로직 외부에 있는게 원인일수도 있을 것 같습니다
![D68184EA-AA70-4F50-B3CA-A1AFB5C547FB_1_105_c](https://github.com/CAU-OSS-2023-Team15/Project-1/assets/12806229/e9a95ecb-626e-48ed-9413-b474b9afcad2)

2023-06-05 17:59 UTC, yymin1022 commented on main.js
> +    let cmd = `cd ${filePath} && git clone \"${http}${github_id}:${github_access_token}@${github_repo_address_substr}\"`;
이부분에서 기존 `git clone` 시 입력했던 계정 정보가 `GithubInfo.txt` 파일로부터 불러와지지 않는 것 같습니다. 자동로그인 로직 추가구현 부탁드려요!

2023-06-05 18:30 UTC, jiyuneel commented on main.js
> +    let cmd = `cd ${filePath} && git clone \"${http}${github_id}:${github_access_token}@${github_repo_address_substr}\"`;
`GithubInfo.txt` 파일이 존재하면 정보를 불러와서 clone을 수행하도록 구현했습니다 👩🏻‍💻

2023-06-05 18:32 UTC, jiyuneel commented on main.js
> +    BrowserWindow.getFocusedWindow().send("refresh");
`refresh` 시그널 로직을 `exec` 로직 외부에 오도록 수정하였더니 해당 문제가 해결되었습니다.!.!

2023-06-06 00:36 UTC, falconlee236 commented on main.js
> +    BrowserWindow.getFocusedWindow().send("refresh");
refresh 시그널 로직을 `exec` 함수 외부에 있으면 안된다는 뜻이죠???
내부에 있어야 한다는 걸로 생각했습니다.

2023-06-06 00:50 UTC, falconlee236 approved these changes
이전에 피드백 했던 UI관련 문제도 잘 해결하였습니다.
제 환경에서 public, private 레포도 잘 클론되고, 사용자 정보도 잘 저장되었습니다.
버튼을 활용해서 visibility를 다루는 점이 인상 깊었습니다.

2023-06-06 04:56 UTC, sehwanii approved these changes
기능적으로, UI적으로 요구사항을 잘 구현하셨네요! 수고하셨습니다!

2023-06-06 06:38 UTC, yymin1022 approved these changes
추가적인 보완사항이 보여서 계속 `Request Changes` 남겼었는데, 하나하나 잘 수정해주셔서 감사합니다 ㅎㅎ
고생하셨어요~!!

2023-06-06 06:38 UTC, merged